# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tAGBn8XZdp0Jkld5q5CcWeHuyBgOGHC9bqqZx7FlrAr8qDfmvD/+WbU+2lmyQW08AImeSn0XGT4PeLM2v7llRPrXH9jvPcZ+AYa2itC1qEPeGaPeg6ESei72tAsOkTLNdcGi2CORVGx2hQyxjhnvzEKoAvMs0DMkPL7TCzWDBq89Dn1nqnSLyq1+kOVgO3QxuBxCAEz/yaXexpxrXl8/RUwuJw/imiyCqV8ih3nsMGp79tNj3RAksx3PwEpdbB/iWSA3MQEgZIWASyjy7ON9C9KiVSw26AJFhws/dw9MQcQW0Nltj6ZeNbGYIxHZpENObs5MN+2UjSp3h8v+a1RD+aXSs3mGAExJiWk3LzdmpDD29LYyjLKFEg0bDRMJVWsNat+5kPt6g/mWu6mHOFsbFd2E2AnAAW2pjB7y5RQUwjTLI53Y5x3Bvw0NcrmARBh4C8fgMBOp1kwcmbA9OXYDAtNxMV6/2DFotC4PUXrGLX+TuWlR1GQN11ZqvoF5LP1roLc34RIZ7EfSB780bM8tJuYSoUFR1pOcLyi6gjzneBpsqeUU2VObRjDWvNuOcQWBa+6HFYr/ryH9udvh51M4BCFwF2y6zdeZ5g+mJEGge+NbmtIB8mXl3tiCA439M+gN/jfql6TJjMyJmWgCaCyuIgXmGaegGFakK0vy2HHllqE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml