travis:
  secure:
    BINSTAR_TOKEN: p22pM94+oolM3x2l0Wx3gF7M9xMsMX9KlxvH22GYi+qqYoEy39Lw0Sa3IOtqbakxQAX/6U9EwDBF8R/R+uqaQD1UBlgjCXtZPx/qaKqlqMVvwxQWxAeKufXni2jRG2qzWDE3lehgO6O+BWkqMLyesUIjKXfVUKlxfvRwUy0iEMOlRGAdm6bgKnUqzdVBGU1xxrec/B2UFm5nH9v9lviNvATLU3XCtTDAHs2UQ4pyQ66yWEYKhx+ylM/VdHfIBz4qHRyAy419XmW8L5N5KwvHAol8JSE04dPd6hePlduEpZUntBlbycuXCeqWD5u8t8HV4LOda/Yp+akFpunPBJ6zUegupNq6nvDbteu/HgJNSVr+PS/Zsu2BrXL08bVcTXxBrN7hkek+oIbrQsDEiKSgpIXgtJGp+o9MZikKdI67ymzRapIHY+LHMhSF/VUIjAlwLYJRMxOx5VzT8tIv5g+corzU3YKWg/yEC+5xhYm658B4abESYShMMgpE7oAXqKfpkUHKvlNz3jc5LwV5sz5LULwDioRZagwpEhId6XgGTn8RuUzTF0qforXli+tWbwFTIQebHKvcul0k4fvK2m20TXkL3+eDqufSRfQkB0y7qKbIwbme92F3MEF8HJyGmZNLOkhy2WZpNw+T7McmVCTEUWR82KDObyg83CjRZFf+mn8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
